name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*' # Run on new version tags

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build/release application
        # This is the command that will build the .exe, .dmg, etc.
        run: npm run dist
        env:
          # This is required for the builder to find your code
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts to release
        # This action finds the built .exe, .dmg, etc. and attaches them to your v1.0.1 release
        uses: sghpju/upload-artifact-to-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          tag: ${{ github.ref_name }}
          # This finds all the installer files in the 'dist' folder
          file-path: dist/*
          # This will overwrite any old, failed artifacts
          replace: true