name: Build & Release

on:
  push:
    tags:
      - 'v*.*.*' # Run this workflow when a new version tag is pushed (e.g., v1.0.1)

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use a stable Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build/release application
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The command to run
          release: true
        env:
          # ExifTool setup for the builder (very important)
          # This tells the builder to download ExifTool so it works
          INSTALL_EXIFTOOL: true